#ifndef PRINTER_CONFIG_HPP
#define PRINTER_CONFIG_HPP

#include <cstddef>

namespace netmap {
    /**
     * @brief Holds configuration settings for result printers.
     *
     * This struct defines visual parameters for the output generated by
     * ResultPrinter derived classes, such as separator characters and line width.
     */
    struct PrinterConfig {
        /** @brief The character used for the main separator lines (e.g., around the title). */
        const char main_sep = '=';
        /** @brief The character used for sub-separators (e.g., under the header). */
        const char sub_sep = '-';
        /** @brief The total width of the printed output. */
        const size_t width = 80;
    };
}

#endif //PRINTER_CONFIG_HPP
